### ISSUE TITLE
build bug in branch foxy

### ISSUE THREAD

**Issue by zjh-de-github** [ros2/rmw_connextdds#138]
**System Info**

- _OS_
  - [e.g. Ubuntu 20.04]
- *ROS version and installation type*
  - [e.g. foxy/binary, rolling/source]
- *RTI Connext DDS version and installation type*
  - [e.g. Pro 5.3.1/apt, Micro 3.0.3/rtipkg]
- *RMW version or commit hash*
  - [e.g. 44cbdc3f45365890921195cf8ed10aaea9633270]

**Bug Description**

In branch foxy,the parameters of function `DDS_DataReader_return_loan_untypedI()` are too many when RTI_DDS_VERSION_MAJOR  > 7. 
The parameter `data_len` should be removed.

**Expected Behavior**

Successfully compiled.

**How to Reproduce**

git switch foxy
colcon build --symlink-install
```

```

**Workarounds**

The parameter `data_len` should be removed.

**Comment by clalancette** [comment]
Ths package isn't supported in Foxy, so it isn't too surprising that it failed.  I'll suggest updating to one of the supported distributions (I can recommend Humble), and trying again.
