### ISSUE TITLE
New release into Rolling

### ISSUE THREAD

**Issue by clalancette** [ros2/rmw_connextdds#24]
@asorbini Could you please do a new release of rmw_connextdds into Rolling?  That should help us get the packages building with all of the recent changes for unique network flows and the like.  Thanks.

**Comment by clalancette** [comment]
I should also add: if you don't have time for it today, just let me know.  I can do the release as well.

**Comment by asorbini** [comment]
@clalancette I was hoping to merge #22 before a new release, and bump the version number to 0.5.0, but from test results and @ivanpauno's review, I see I still have some work on that, and probably won't be able to merge it before tomorrow at the earliest, to allow for any additional review (assuming I'll be able to get the code in final shape today).

If you can do the release today I would appreciate it. Maybe bump the version to 0.4.1? (or 0.5, and we'll go to 0.6 after #22)

Thanks!

**Comment by clalancette** [comment]
Sounds good, I'll go ahead and do it.  Numbers are cheap, we can always bump again :).  Thanks for the reply.

**Comment by asorbini** [comment]
@clalancette I'm going to let CI run overnight to validate the recent changes (#22, #28). If everything is as expected, I'll go ahead and create `0.6.0` tomorrow.

**Comment by asorbini** [comment]
CI was green/as expected, going ahead with 0.6.0 release now.

For reference:
- nightly_linux_release: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=nightly_linux_release&build=1885)](https://ci.ros2.org/view/nightly/job/nightly_linux_release/1885/)
- nightly_osx_release: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=nightly_osx_release&build=2028)](https://ci.ros2.org/view/nightly/job/nightly_osx_release/2028/)
- nightly_win_rel: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=nightly_win_rel&build=1903)](https://ci.ros2.org/view/nightly/job/nightly_win_rel/1903/)
- Rci__nightly-connext_ubuntu_focal_amd64: [![Build Status](https://build.ros2.org/buildStatus/icon?job=Rci__nightly-connext_ubuntu_focal_amd64&build=294)](https://build.ros2.org/view/Rci/job/Rci__nightly-connext_ubuntu_focal_amd64/294/)

**Comment by asorbini** [comment]
Tagged and bloomed `0.6.0` (ros/rosdistro#29138)
