### ISSUE TITLE
New minor release into Rolling/Galactic

### ISSUE THREAD

**Issue by clalancette** [ros2/rmw_connextdds#46]
@asorbini I was going to do a new minor release into both rolling and galactic, 0.6.1.  This will get one more fix into Galactic that is pending, and it is just easier at this point to keep Rolling >= to Galactic.  Any objections?

**Comment by asorbini** [comment]
Sounds good, thank you for the heads up.

I'm assuming the fix you are referring to is #43?

**Comment by clalancette** [comment]
> I'm assuming the fix you are referring to is #43?

Ah, no, it looks like the fix that is already committed is #33; that's the one I wanted to release to both Galactic and Rolling.  Still OK?

**Comment by asorbini** [comment]
Oh right, forgot about that. Still all good 👍🏼

**Comment by clalancette** [comment]
https://github.com/ros/rosdistro/pull/29306 and https://github.com/ros/rosdistro/pull/29307 are open.  They aren't merged yet, but I'll do a pass a little later on (or tomorrow morning) and merge them.  So I'll close this out, thanks for the feedback!
