### ISSUE TITLE
Release of 0.6.2 into Galactic

### ISSUE THREAD

**Issue by clalancette** [ros2/rmw_connextdds#58]
@asorbini FYI, I'm going to do a release of 0.6.2 into Galactic to get #54 included in the binary packages.

Relatedly, this means that the next time we do a release into Rolling, we *must* remember to bump the minor on it (this would be 0.7.0).  That's so that we leave room in the patch numbers for any further updates to Galactic.  If you'd prefer, I can do a Rolling release of 0.7.0 right now so we don't forget later.  Or we can just do it later.  Either is fine with me, just let me know what you'd like.

**Comment by asorbini** [comment]
@clalancette sorry for the delay in reply, I was out for a few days. Thank you for taking care of this. We'll keep in mind the required bump of minor version for the next release into Rolling!
