### ISSUE TITLE
Communication between different domain ID.

### ISSUE THREAD

**Issue by sumitpaulde** [ros2/rmw_connextdds#78]
Hi, I would like to know how can we establish communication between different DDS domain_ids while using Connextdds.

```
RMW_IMPLEMENTATION=rmw_connextdds \
 ROS_DOMAIN_ID=5 \
  ros2 run demo_nodes_cpp add_two_ints_server

RMW_IMPLEMENTATION=rmw_fastrtps_cpp \
ROS_DOMAIN_ID=10 \
  ros2 run demo_nodes_cpp add_two_ints_client
```

For other DDS implementation as, Cyclone DDS there is zenoh_bridge_dds to support this kind of connectivity. I am unable to find any framework or library to support the different domain connectivity for Connext_DDS. Please suggest me.

**Comment by asorbini** [comment]
Hi @sumitpaulde,

I'm not sure what your goal is. DDS domain are specifically designed to be isolated from one another.

If you want to have two applications in different domains communicate with each other, you will need to create a third application that operates in both domains and acts as a bridge between the two.

[RTI Routing Service](https://www.rti.com/products/is/routing-service) can provide a solution to to this use case, beside many other integrations thanks to its extensible plugin framework.
