### ISSUE TITLE
Humble debian package doesn't contain binaries

### ISSUE THREAD

**Issue by Aposhian** [ros2/rmw_connextdds#89]
**System Info**

- _OS_
  - Ubuntu 22.04
- *ROS version and installation type*
  - humble binary
- *RTI Connext DDS version and installation type*
  - 6.0.1 debian packages
- *RMW version or commit hash*
  - 0.11.1-1jammy.20220520.011125

**Bug Description**
Installing `ros-humble-rmw-connextdds` does not install the `librmw_connextdds.so` library.

**Expected Behavior**
On galactic I can do the following:
```
docker run -e RTI_NC_LICENSE_ACCEPTED=yes ros:galactic bash -c "apt-get update && apt-get install -y ros-galactic-rmw-connextdds && find /opt/ros/galactic/lib -name 'librmw_connextdds*'"
```
and see
```
/opt/ros/galactic/lib/librmw_connextdds_common_pro.so
/opt/ros/galactic/lib/librmw_connextdds.so
```

**How to Reproduce**

But on humble the equivalent command
```
docker run -e RTI_NC_LICENSE_ACCEPTED=yes ros:humble bash -c "apt-get update && apt-get install -y ros-humble-rmw-connextdds && find /opt/ros/humble/lib -name 'librmw_connextdds*'"
```

yields an empty result.

**Workarounds**
I could build from source, but I would like not to.

**Additional context**
I wondered if it was a package install/configuration issue. But I manually downloaded `ros-humble-rmw-connextdds` and `ros-humble-rmw-connextdds-common` manually and inspected them, and neither contains any binaries.

**Comment by asorbini** [comment]
I just verified that the Debian package now correctly contains the libraries, so I'm closing this issue.

To reproduce:
```sh
docker run -ti --rm osrf/ros:humble-desktop
apt-get update
apt-get install -y ros-humble-rmw-connextdds
source /opt/ros/humble/setup.bash
RMW_IMPLEMENTATION=rmw_connextdds ros2 run demo_nodes_cpp talker
```
