### ISSUE TITLE
ROS2 Humble Support Unclear

### ISSUE THREAD

**Issue by cgarry-vs** [ros2/rmw_connextdds#90]
I do not see support for ROS2 Humble in the README, but setup instructions are in the Humble documentation:
https://docs.ros.org/en/humble/Installation/DDS-Implementations.html

**Implementation Considerations**

Clarify/fix documentation.

**Comment by clalancette** [comment]
Good point.  Would you mind opening a PR to add it into that table (along with Galactic)?  Thanks!
